### ISSUE TITLE
Switch commented scheme to propTypes type-checking.

### ISSUE THREAD

**Issue by yasserhennawi** [halaelsaka2/go-between-FrontEnd#77]
Instead of using comments for describe how components should word (as long as they are simple) we can use propTypes only.
https://github.com/halaelsaka2/go-between-FrontEnd/blob/99e49c78b5da16c04d3b638584a9b9144f1a4014/src/components/DescriptionScetion/index.jsx#L3-L11

**Comment by salmawagdy96** [comment]
done

**Comment by salmawagdy96** [comment]
done for best-section components
